name: thaiqr
description: "A Flutter package for generating Thai QR codes compliant with the PromptPay standard."
version: 1.1.0
homepage: https://github.com/chawatvish/ThaiQR_Flutter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/